### PR TITLE
not throwing error when depends doesn't exist

### PR DESCRIPTION
**Pull request by deanmalmgren**
@frrmack noticed that the following task didn't throw an error when `src/write_hello_world2.py` didn't exist.

``` yaml

---
creates: hello_world.txt
depends: src/write_hello_world2.py # this file doesn't exist
command: python {{depends}} > {{creates}}
```

### CODE REVIEW

**Comment by deanmalmgren** [comment]
@frrmack is this still a problem? When I tried to run that same exact example (off of the latest `master` commit db693d22a3b00450bad5e58b8adea34e7a033289) I see something that looks like this:

screen shot 2014-05-13 at 10 21 39 am

Were you hoping for something more explicit? Maybe highlighting error message in red?

**Comment by frrmack** [comment]
I'm not sure if this is crucial at all, this output in this case is totally
fine I think.

When we talked about it, I think you said that _flo_ should throw an error
message saying the dependency doesn't exist. I'm not sure if that is really
necessary, but I think the idea was this:

Because it is a dependency, if the dependency does not exist, I would
expect the command to not run. Here, the command runs, but the command
itself throws an error when it hits the need for the dependency. In this
case, this happens instantaneously and pretty much the outcome is the same,
there is an error, and you can see why.

Perhaps in other cases, where the lack of the dependency file does not lead
to a clear error from the command itself, or if the command ends in an
error due to the lack of dependency after a full hour of running, it may be
better if flo threw an error before actually running the code and doesn't
run it. But I can't think of an actual, tangible example from real life
experience for this case right now, which most likely means that this would
be a fringe issue, if a real issue at all, so I don't think this is a high
priority problem.

On Tue, May 13, 2014 at 10:26 AM, Dean Malmgren notifications@github.comwrote:

> @frrmack https://github.com/frrmack is this still a problem? When I
> tried to run that same exact example (off of the latest master commit
> db693d2https://github.com/deanmalmgren/flo/commit/db693d22a3b00450bad5e58b8adea34e7a033289)
> I see something that looks like this:
> 
> [image: screen shot 2014-05-13 at 10 21 39 am]https://cloud.githubusercontent.com/assets/255672/2959383/56b583b2-dab2-11e3-96c8-714728f54263.png
> 
> Were you hoping for something more explicit? Maybe highlighting error
> message in red?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/deanmalmgren/flo/issues/59#issuecomment-42970081
> .

## 

---

_irmak sirer_
partner, data scientist

_datascope analytics_
http://datascopeanalytics.com

twitter: @frrmack https://twitter.com/frrmack
cell: +1.224.522.5966

**Comment by deanmalmgren** [comment]
@frrmack thanks for clarifying. i think you're right that the command shouldn't run at all. this will become that much more important when we expand the functionality to allow for database protocols, hdfs, etc.

**Comment by frrmack** [comment]
No problem! Say hi to Ian for me : )

On Tue, May 13, 2014 at 2:37 PM, Dean Malmgren notifications@github.comwrote:

> @frrmack https://github.com/frrmack thanks for clarifying. i think
> you're right that the command shouldn't run at all. this will become that
> much more important when we expand the functionality to allow for database
> protocols, hdfs, etc.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/deanmalmgren/flo/issues/59#issuecomment-43001982
> .

## 

---

_irmak sirer_
partner, data scientist

_datascope analytics_
http://datascopeanalytics.com

twitter: @frrmack https://twitter.com/frrmack
cell: +1.224.522.5966

**Comment by frrmack** [comment]
No problem! Happy to help. Say hi to Ian for me : )

On Tue, May 13, 2014 at 2:37 PM, Dean Malmgren notifications@github.comwrote:

> @frrmack https://github.com/frrmack thanks for clarifying. i think
> you're right that the command shouldn't run at all. this will become that
> much more important when we expand the functionality to allow for database
> protocols, hdfs, etc.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/deanmalmgren/flo/issues/59#issuecomment-43001982
> .

## 

---

_irmak sirer_
partner, data scientist

_datascope analytics_
http://datascopeanalytics.com

twitter: @frrmack https://twitter.com/frrmack
cell: +1.224.522.5966

**Comment by deanmalmgren** [comment]
haha. will do...as soon as he wakes up. he's sleeping on katie at the moment :)

**Comment by deanmalmgren** [comment]
now the error message looks something like this, which i think is much better.

screen shot 2014-05-13 at 2 45 02 pm

**Comment by frrmack** [comment]
Looks awesome!

On Tue, May 13, 2014 at 3:00 PM, Dean Malmgren notifications@github.comwrote:

> Merged #59 https://github.com/deanmalmgren/flo/pull/59.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/deanmalmgren/flo/pull/59#event-120735088
> .

## 

---

_irmak sirer_
partner, data scientist

_datascope analytics_
http://datascopeanalytics.com

twitter: @frrmack https://twitter.com/frrmack
cell: +1.224.522.5966

**Pull request merged**
