### PR TITLE
get rid of alias

### PR DESCRIPTION
**Pull request by deanmalmgren**
This is a little redundant given the fact that we have autocomplete incorporated into workflow. This has the added benefit of making the internal code a bit simpler.

### CODE REVIEW

**Comment by deanmalmgren** [comment]
@ahwolf before we get rid of aliases, are you using them at all?

**Comment by ahwolf** [comment]
Nope.

**Comment by deanmalmgren** [comment]
I started to get rid of `alias`, but before I merge this, I'd like to see what happens with #11, which has a pretty compelling use case for an alias. This is also described in the [design specification](https://github.com/deanmalmgren/data-workflow/blob/master/design/workflow.yaml#L42-L61). If anyone has any workarounds for these...

**Comment by deanmalmgren** [comment]
In digging into the regexp implementation in issue #11 a bit, I'm realizing that getting rid in favor of `tags` as described in #45 would be pretty nice. When `Task`s are dynamically added to the `TaskGraph` that match a particular regular expression, it'd be nice for those tasks to be able to re-use the `tags` in their `commands` definition. Then its explicit that these `alias`es are _not_ unique.

**Pull request merged**
