### PR TITLE
make dependency graph traversal deterministic

### PR DESCRIPTION
**Pull request by deanmalmgren**
In the event there are ties in the dependency graph, @mstringer suggested that we make sure that things are always run in the same order. Originally we discussed alphabetical but settled on running things in the same order that they appear in the YAML configuration file.

### CODE REVIEW

**Comment by deanmalmgren** [comment]
@mstringer what order would you expect [this example](https://github.com/deanmalmgren/flo/tree/96948ee771785eb23d9e6e6cb479b6fd2adb0408/examples/deterministic-order) to run in? (reproduced below for convenience)

``` yaml
---
creates: data/a
command:
  - mkdir -p $(dirname {{creates}})
  - echo "x" > {{creates}}

---
creates: data/b
command: echo "x" > {{creates}}

---
creates: data/e
depends: data/a
command: echo "x" > {{creates}}

---
creates: data/f
depends: data/a
command: echo "x" > {{creates}}

---
creates: data/g
depends: data/a
command: echo "x" > {{creates}}

---
creates: data/h
depends: data/a
command: echo "x" > {{creates}}

---
creates: data/i
depends: data/a
command: echo "x" > {{creates}}

---
creates: data/j
depends: data/a
command: echo "x" > {{creates}}

---
creates: data/n
depends: 
  - data/j
  - data/m
command: echo "x" > {{creates}}

---
creates: data/c
command: echo "x" > {{creates}}

---
creates: data/l
depends: data/c
command: echo "x" > {{creates}}

---
creates: data/d
command: echo "x" > {{creates}}

---
creates: data/m
depends: data/d
command: echo "x" > {{creates}}

---
creates: data/k
depends: data/b
command: echo "x" > {{creates}}
```

**Comment by deanmalmgren** [comment]
I'm going to close this out for now, @mstringer. The order is deterministic but I'm not necessarily convinced that its in an order that people would intuitively expect. Maybe we can discuss in person sometime.

**Comment by mstringer** [comment]
Hi @deanmalmgren, I think you might be referencing the wrong GitHub user.  I have literally no idea what you're talking about :)

I hope you find them!
- @mstringer

**Comment by deanmalmgren** [comment]
@mstringer -- thanks! I meant my buddy @stringertheory.

**Pull request merged**
